### ISSUE TITLE
Lines 13-17

### ISSUE THREAD

**Issue by idlesummer** [Quarntime/Manga-Downloader#1]
What do these actually do?
```python
frame = tk.Frame(root, bg=cf.BGCOLOR)
frame.place(relwidth=1,relheight=.8,rely=.25)

label = tk.Label(root, text='Manga Downloader')
label.place(relheight=.1, relx=.01)
```

**Comment by Lorgborg** [comment]
the frame provides the widget where the results come in. The label is located on the upper left of the GUI and is the name of the app 'Manga Downloader'.
